[tool.poetry]
name = "opencity"
version = "0.1.0"
description = ""
authors = ["sairam4123 <opencity@info.github.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"
kivy = {version = "2.0.0rc3", extras = ["all"]}
cryptography = "^3.0"
Cython = "3.0a6"
"kivy_deps.sdl2" = "0.1.*"
"kivy_deps.glew" = "0.1.*"
"kivy_deps.gstreamer" = "0.1.*"
"kivy_deps.angle" = "0.1.*"
pillow = "^7.2.0"
python-ffmpeg = "^1.0.11"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
